### ISSUE TITLE
aarch64 migration bot errored

### ISSUE THREAD

**Issue by Cadair** [conda-forge/cspice-feedstock#38]
👋  I am trying to add aarch64 builds to sunpy, and cspice is now the last parent needed to make that work, however the migration bot has failed on this repo: https://github.com/regro/cf-scripts/actions/runs/12004222275/job/33458864882#step:7:2649

I am not sure what the problem is but opening this in the hope that me or someone else remembers to look.

**Comment by Cadair** [comment]
Just in case: @conda-forge-admin, please rerender

**Comment by AndrewAnnex** [comment]
@Cadair I'm confused, aarch64 for linux and macos arm64 are already supported as far as I recall and I can see those artifacts hosted on https://anaconda.org/conda-forge/cspice/files and you can see both architectures in the supported platforms already. Why is this or #40 necessary?

**Comment by Cadair** [comment]
Well #40 was largely me blindly trying to prevent the bot erroring, I assume the bot was also trying to enable ppc64le as well as aarch64. I don't know the workings of the migration bot, but it clearly thinks it has work to do here.

**Comment by AndrewAnnex** [comment]
@Cadair, I don't think the bot is necessary then, I don't know why conda forge has that bot also attempting ppc64le, but as it's not a supported platform anyways for cspice and the migration bot for aarch64 already occurred I'll close both this issue and your pr unless there is something I am missing

**Comment by Cadair** [comment]
My PR is mostly general clean up from the linter, so you might want to consider merging it anyway (maybe without the ppc64le bit). Let's reach out to @conda-forge/core or someone who can help us figure out why the bot thinks it needs to migrate this package for aarch64/ppc64le if there are already aarch64 builds. Maybe we just need to skip ppcle64 or something as it's unsupported?

**Comment by AndrewAnnex** [comment]
yeah if you could open an issue that'd be super helpful, as I suppose it could be that parsing issue, but probably shouldn't be the default behavior of that bot anyways. Given the impending holiday for me I'll work to just resolve the bigger linting issues for the moment.

**Comment by xhochy** [comment]
If you don't build for ppc64le, then please don't merge or close the migrator PR as that will signal ppc64lr support. Keep it in draft.

**Comment by Cadair** [comment]
The issue is the PR never opened. Is there a way I can have the migrator run on downstream packages without having it run here first?

**Comment by AndrewAnnex** [comment]
@xhochy okay copy I'll leave that PR open. I also don't understand the root issue here, considering this feedstock was migrated a while ago to include aarch64 support, why did the bot run again in the first place?

**Comment by xhochy** [comment]
The root issue of the bot not appearing is that conda-smithy rerender is failing with:

```
Traceback (most recent call last):
  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_build/metadata.py", line 2003, in _get_contents
    rendered = template.render(environment=env)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/tmp/tmpqyfdtspg/cspice-feedstock/recipe/meta.yaml", line 12, in top-level template code
    {% set sha256 = "0deae048443e11ca4d093cac651d9785d4f2594631a183d85a3d58949f4d0aa9" %}  # [osx-arm64]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'platform_segment' is undefined
```

Still, the root issue of this issue is that the package is migrated for aarch64, but the aarch64&ppc64le migrator doesn't proceed past this package as the aarch64&ppc64le PR has not been merged (and never will).

@Cadair you either need to manually proceed or help in splitting up the aarch64/ppc64le migrator into two. Personally, I would like to see this but am not spending time on this as it might be a bit of work.

**Comment by AndrewAnnex** [comment]
okay with #40 merged I suspect this issue could be closed as it's some issue ultimately now with the migrator bot, presumably it would now work against this feedstock but it shouldn't proceed to attempt to add ppc64le as the original desire for aarch64/arm64 builds is already achieved

**Comment by jakirkham** [comment]
The issues with the bot migration are due to the recipe itself using Jinja variables that are undefined in the cases the bot is trying to handle

Please see these comments: https://github.com/conda-forge/cspice-feedstock/pull/40#pullrequestreview-2459732808
